name: Telegram Bot Update

on:
  push:
    branches:
      - main

jobs:
  update-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Update bot code
        run: ./update-bot-script.sh
      - name: Commit and push changes
        run: git add . && git commit -m "Automated update" && git push origin main
